### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by jed-code** [videosdk-live/videosdk-rtc-react-native-sdk-example#14]
![error](https://user-images.githubusercontent.com/56468464/181253993-9b3f4373-e204-4263-9637-33245675306a.PNG)

**Comment by sagarkava** [comment]
Hello @jed-code 
Passed the token, meeting id, userName and URL.

**Comment by sagarkava** [comment]
Apart from that, for tech support, can you please join Video SDK discord server - https://discord.gg/Gpmj6eCq5u
