### ISSUE TITLE
React Native 0.70.1 version app issue

### ISSUE THREAD

**Issue by Dhruti-TerminalTrend** [videosdk-live/videosdk-rtc-react-native-sdk-example#16]
I upgraded my react native Version to 0.70.1 and when i create the meeting it is showing me you left the meeting automatically

**Comment by ahmedbhesaniya97** [comment]
Hi @Dhruti-TerminalTrend,
Thanks for raising it.
Can you specify your `React` and `@videosdk.live/react-native-sdk` package version as well as in which platform(Android/iOS) are you getting this issue

**Comment by ahmedbhesaniya97** [comment]
Hi @Dhruti-TerminalTrend,
It is resolved in latest commits.
