### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by salman-kryptomind** [videosdk-live/videosdk-rtc-react-native-sdk-example#24]
I've downloaded Tester app from Firebase Distribution and it is crashing as soon as tap "Join a Meeting" button.

**Comment by arjun-kava** [comment]
Hey, @salman-kryptomind This is a known issue and we are working on it. We will update you soon. Thanks.

**Comment by michaelmowry** [comment]
I am having trouble with dependencies on npm install

**Comment by rajansurani** [comment]
@michaelmowry Can you share the error logs?

**Comment by rajansurani** [comment]
@salman-kryptomind Please update the app from Firebase Distribution. The Crash on "Join a Meeting" button has been fixed
