### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by salmandayal** [videosdk-live/videosdk-rtc-react-native-sdk-example#27]
After successfully doing the setup I ran the project it worked fine. But after a day I tried running it again it didn't work but after few tries it worked eventually. But now I am stuck on the same error I have attached the screenshot below.

<img width="647" alt="Screenshot 2023-02-08 at 12 18 18 AM" src="https://user-images.githubusercontent.com/17268239/217441041-93b05356-ebc2-4bc4-86f0-921e1636752a.png">

VideoSDK Details:
"@videosdk.live/react-native-incallmanager": "0.0.9",
"@videosdk.live/react-native-sdk": "0.0.41",

System Information:

System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.48 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mac/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.7 
    react-native-macos: Not Found

**Comment by ahmedbhesaniya97** [comment]
@salmandayal 
I think this might solve your problem.

```
rm -rf node_modules
npm install
npm run android
```

**Comment by salmandayal** [comment]
@ahmedbhesaniya97 Already tried that! didn't. worked. Android SDK: Not Found is not issue as other of my projects are already building and running.

**Comment by salmandayal** [comment]
@ahmedbhesaniya97 Is there some configuration required for "@videosdk.live/react-native-incallmanager"? As it not mentioned in docs. Can you guide regarding that.

**Comment by salmandayal** [comment]
What do you need to look more into the issue?
